import {
  Trash2,
  CirclePlus,
  CircleMinus,
  Sparkle,
  Sparkles,
  Info,
  Brain,
  CalendarDays,
  Split,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  X,
  BarChart3,
  MoreHorizontal,
  FastForward,
  Activity,
} from 'lucide-react';

export const AppIcons = {
  trash: Trash2,
  add: CirclePlus,
  remove: CircleMinus,
  sparkle: Sparkle,
  sparkles: Sparkles,
  info: Info,
  brain: Brain,
  calendar: CalendarDays,
  split: Split,
  link: ExternalLink,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  close: X,
  chart: BarChart3,
  moreHorizontal: MoreHorizontal,
  skip: FastForward,
  status: Activity,
};

export type IconName = keyof typeof AppIcons;
