name: Build & Test

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITE_STATUS_URL: ${{ secrets.STATUS_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test --coverage

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      VITE_STATUS_URL: ${{ secrets.STATUS_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn build-storybook
